const posts = [
    {
      _id: '1',
      userId: '643059c59d990055ea7bb742',
      username: 'David',
      description: 'Had an amazing meal at a local restaurant today!',
      location: 'Nashville',
      userImage: 'david',
      postImage: 'https://example.com/post1.jpg',
      likes: 20,
      dislikes: 2,
    },
    {
      _id: '2',
      userId: '643059c59d990055ea7bb743',
      username: 'Maxx',
      description: 'Cooked an awesome dinner tonight!',
      location: 'Savannah',
      userImage: 'maxx',
      postImage: 'https://example.com/post2.jpg',
      likes: 12,
      dislikes: 1,
    },
    {
      _id: '3',
      userId: '643059c59d990055ea7bb744',
      username: 'Victor',
      description: 'Tried a new restaurant and it was terrible :(',
      location: 'Berlin',
      userImage: 'victor',
      postImage: 'https://example.com/post3.jpg',
      likes: 3,
      dislikes: 18,
    },
    {
      _id: '4',
      userId: 'ChefBoyarD',
      username: '643059c59d990055ea7bb745',
      description: 'Made some delicious cookies for dessert!',
      location: 'Atlanta',
      userImage: 'daikeen',
      postImage: 'https://example.com/post4.jpg',
      likes: 8,
      dislikes: 0,
    },
    {
      _id: '5',
      userId: '643059c59d990055ea7bb746',
      username: 'Sarah',
      description: 'Had an amazing brunch this morning!',
      location: 'Atlanta',
      userImage: 'sarah',
      postImage: 'https://example.com/post5.jpg',
      likes: 15,
      dislikes: 3,
    },
  ];
  
  export default posts;